#* Btop++ Configuration File

#* Color theme
color_theme = "catppuccin_mocha"

#* Update time in milliseconds
update_ms = 2000

#* Processes sorting
proc_sorting = "cpu lazy"

#* Reverse sorting
proc_reversed = False

#* Show processes as a tree
proc_tree = False

#* Use cpu custom graph colors
cpu_graph_upper = "total"
cpu_graph_lower = "total"

#* Show cpu box
cpu_box = True

#* Show memory box
mem_box = True

#* Show network box
net_box = True

#* Show processes box
proc_box = True

#* Show battery box
bat_box = True

#* Show clock
clock_box = True

#* Show uptime
uptime_box = True

#* Show system uptime
system_uptime = True

#* Show load average
load_box = True

#* Show process info box
proc_info_box = True

#* Show disk usage
disk_box = True

#* Show swap usage
swap_box = True

#* Show gpu usage
gpu_box = True

#* Use 24h clock
time_24h = True

#* Use celsius
temp_scale = "celsius"

#* Use gradients
gradient_mode = True

#* Use truecolor
truecolor = True

#* Use rounded corners
rounded_corners = True

#* Use background color
background_update = True

#* Use vim keys
vim_keys = True

#* Use mouse support
mouse_support = True
